{{- if .Values.deployment.enabled}}
apiVersion: apps/{{.Values.deployment.apiVersion}}
kind: Deployment
metadata:
  name: {{template "meep.fullname" .}}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{.Values.deployment.replicaCount}}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.deployment.matchLabels}}
      {{$key}}: {{$value | quote}}
      {{- end}}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        {{- range $key, $value := .Values.deployment.template.labels}}
        {{$key}}: {{$value | quote}}
        {{- end}}

    spec:
      containers:
      {{- if not .Values.external.enabled}}
      {{- with .Values.deployment}}
        - name: {{.image.name}}
        {{- if .image.tag}}
          image: {{.image.repository}}:{{.image.tag}}
        {{else}}
          image: {{.image.repository}}
        {{- end}}
          imagePullPolicy: {{.image.pullPolicy}}
        {{- if .image.command.enabled}}
          command:
          {{- range $cmd := .image.command.command}}
            - {{$cmd}}
          {{- end}}
          args:
          {{- range $arg := .image.command.args}}
            - {{$arg}}
          {{- end}}
        {{- end}}
        {{- if .image.envvar.enabled}}
          env:
          {{- range $key, $val := .image.envvar.env}}
            - name: {{$key}}
              value: {{$val | quote}}
          {{- end}}
        {{- end}}
          resources:
{{toYaml .resources | indent 12}}
      terminationGracePeriodSeconds: {{.terminationGracePeriodSeconds}}
      {{- end}}
      {{- end}}

      nodeSelector:
{{toYaml .Values.deployment.nodeSelector | indent 8}}

      affinity:
{{toYaml .Values.deployment.affinity | indent 8}}

      tolerations:
{{toYaml .Values.deployment.tolerations | indent 8}}
{{- end}}
