# Default values for meep-metrics-engine
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-metrics-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependencies:
    system:
      - kube-dns
    namespace:

image:
  repository: meep-docker-registry:30001/meep-metrics-engine
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    MEEP_SVC_PATH: /metrics/v2
    MEEP_HOST_URL: {{ .HostUrl }}

service:
  name: meep-metrics-engine
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/metrics
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/metrics(/|$)(.*)$ /metrics/$2 break;
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-metrics-engine&sbox={{ .SandboxName }}
    {{- end }}
  labels: {}
  tls:

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s
    
codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-metrics-engine"

meepOrigin: core
