---
swagger: "2.0"
info:
  description: "This API enables the Metrics Service to post metrics measurements/events\
    \ to edge applications <p>**Micro-service**<br>None <p>**Type & Usage**<br>User's\
    \ Edge Applications subscribing to Metrics measurements/events must implement\
    \ this API <p>**Details**<br>API details available at _your-AdvantEDGE-ip-address/api_\
    \ <p>**Note**<br>This API is not exposed by default on the AdvantEDGE platform"
  version: "1.0.0"
  title: "AdvantEDGE Metrics Service Notification REST API"
  contact:
    name: "InterDigital AdvantEDGE Support"
    email: "AdvantEDGE@InterDigital.com"
  license:
    name: "Apache 2.0"
    url: "https://github.com/InterDigitalInc/AdvantEDGE/blob/master/LICENSE"
basePath: "/sandboxname/metrics-notif/v2"
tags:
- name: "notifications"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /network/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Metrics Service to issue\
        \ a callback notification towards an ME application with a Network Metrics\
        \ subscription"
      description: "Network metrics subscription notification"
      operationId: "postNetworkNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Network Notification"
        required: true
        schema:
          $ref: "#/definitions/NetworkNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
  /event/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Metrics Service to issue\
        \ a callback notification towards an ME application with an Event subscription"
      description: "Events subscription notification"
      operationId: "postEventNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Event Notification"
        required: true
        schema:
          $ref: "#/definitions/EventNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
definitions:
  NetworkNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ Network Subscription operation."
      networkMetricList:
        $ref: "#/definitions/NetworkMetricList"
    description: "Network notification - callback generated toward an ME app with\
      \ a network subscription"
    example:
      callbackData: "1234"
      networkMetricList:
        columns:
        - "time"
        - "lat"
        - "ul"
        - "dl"
        - "ulos"
        - "dlos"
        values:
        - time: "2019-11-24T12:45:00-5:00"
          lat: 5
          ul: 100000.0
          dl: 90000.0
          ulos: 0.001
          dlos: 0.003
        - time: "2019-11-24T12:45:01-5:00"
          lat: 5
          ul: 100000.0
          dl: 90000.0
          ulos: 0.001
          dlos: 0.003
        name: "network metrics"
  NetworkMetricList:
    type: "object"
    properties:
      name:
        type: "string"
        example: "network metrics"
        description: "Response name"
      columns:
        type: "array"
        description: "columns included in response based on queried values"
        items:
          type: "string"
          description: "Queried value"
      values:
        type: "array"
        items:
          $ref: "#/definitions/NetworkMetric"
    description: "Network metrics query response"
    example:
      columns:
      - "time"
      - "lat"
      - "ul"
      - "dl"
      - "ulos"
      - "dlos"
      values:
      - time: "2019-11-24T12:45:00-5:00"
        lat: 5
        ul: 100000.0
        dl: 90000.0
        ulos: 0.001
        dlos: 0.003
      - time: "2019-11-24T12:45:01-5:00"
        lat: 5
        ul: 100000.0
        dl: 90000.0
        ulos: 0.001
        dlos: 0.003
      name: "network metrics"
  NetworkMetric:
    type: "object"
    properties:
      time:
        type: "string"
        example: "2019-11-24T12:45:00-5:00"
        description: "Time of network metrics"
      lat:
        type: "integer"
        example: 5
        description: "Round-trip latency (ms)"
      ul:
        type: "number"
        format: "double"
        example: 90.1
        description: "Uplink throughput from src to dest (Mbps)"
      dl:
        type: "number"
        format: "double"
        example: 100.0
        description: "Downlink throughput from dest to src (Mbps)"
      ulos:
        type: "number"
        format: "double"
        example: 0.001
        description: "Uplink packet loss from src to dest (%)"
      dlos:
        type: "number"
        format: "double"
        example: 0.003
        description: "Uplink packet loss from dest to src (%)"
    description: "Value of a single network metric"
    example:
      time: "2019-11-24T12:45:00-5:00"
      lat: 5
      ul: 100000.0
      dl: 90000.0
      ulos: 0.001
      dlos: 0.003
  EventNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ Event Subscription operation."
      eventMetricList:
        $ref: "#/definitions/EventMetricList"
    description: "Event notification - callback generated toward an ME app with an\
      \ event subscription"
    example:
      callbackData: "1234"
      eventMetricList:
        columns:
        - "event"
        values:
        - event: "JSON-formatted mobility event ue1 to poa3"
          time: "2019-11-24T12:45:00-5:00"
        - event: "JSON-formatted mobility event ue1 to poa2"
          time: "2019-11-24T12:44:01-5:00"
        name: "event metrics"
  EventMetricList:
    type: "object"
    properties:
      name:
        type: "string"
        example: "event metrics"
        description: "Response name"
      columns:
        type: "array"
        description: "columns included in response based on queried values"
        items:
          type: "string"
          description: "Queried value"
      values:
        type: "array"
        items:
          $ref: "#/definitions/EventMetric"
    description: "Event metrics query response"
    example:
      columns:
      - "event"
      values:
      - event: "JSON-formatted mobility event ue1 to poa3"
        time: "2019-11-24T12:45:00-5:00"
      - event: "JSON-formatted mobility event ue1 to poa2"
        time: "2019-11-24T12:44:01-5:00"
      name: "event metrics"
  EventMetric:
    type: "object"
    properties:
      time:
        type: "string"
        example: "2019-11-24T12:45:00-5:00"
        description: "Time of event metrics"
      event:
        type: "string"
        example: "JSON-formatted mobility event ue1 to poa3"
        description: "JSON-fomatted event"
    description: "Value of a single event metric"
    example:
      event: "JSON-formatted mobility event ue1 to poa3"
      time: "2019-11-24T12:45:00-5:00"
externalDocs:
  description: "GitHub Wiki"
  url: "https://github.com/InterDigitalInc/AdvantEDGE/wiki"
