# Default values for meep-gis-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-gis-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependency: kube-dns

image:
  repository: meep-docker-registry:30001/meep-gis-engine
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    MEEP_SESSION_KEY: {{ .SessionKey }}

service:
  name: meep-gis-engine
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/gis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-gis-engine&sbox={{ .SandboxName }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/gis(/|$)(.*)$ /gis/$2 break;
  labels: {}
  tls:

codecov:
  enabled: false

meepOrigin: core

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
