# Default values for meep-sandbox-ctrl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-sandbox-ctrl

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  altPort: 8080
  dependency: kube-dns


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-docker-registry:30001/meep-sandbox-ctrl
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    MEEP_HOST_URL: {{ .HostUrl }}
    MEEP_SESSION_KEY: {{ .SessionKey }}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/api
        - /{{ .SandboxName }}/alt/api
        - /{{ .SandboxName }}/sandbox-ctrl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/api$ $scheme://$http_host/{{ .SandboxName }}/api/ permanent;
      rewrite ^/{{ .SandboxName }}/alt/api$ $scheme://$http_host/{{ .SandboxName }}/alt/api/ permanent;
      rewrite ^/{{ .SandboxName }}/api(/|$)(.*)$ /api/$2 break;
      rewrite ^/{{ .SandboxName }}/alt/api(/|$)(.*)$ /alt/api/$2 break;
      rewrite ^/{{ .SandboxName }}/sandbox-ctrl(/|$)(.*)$ /sandbox-ctrl/$2 break;
  labels: {}
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

user:
  swagger:
    enabled: {{ .UserSwagger }}
    location: {{ .UserSwaggerDir }}
    mountpath: "/user-swagger"
    servepath: "/user-swagger-sandbox"
codecov:
  enabled: false

meepOrigin: core
