# Default values for meep-sandbox-ctrl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-sandbox-ctrl

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  altPort: 8080
  dependencies:
    system:
      - kube-dns
    namespace:

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists

image:
  repository: meep-docker-registry:30001/meep-sandbox-ctrl
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    MEEP_SVC_PATH: /sandbox-ctrl/v1
    MEEP_HOST_URL: {{ .HostUrl }}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/api
        - /{{ .SandboxName }}/alt/api
        - /{{ .SandboxName }}/sandbox-ctrl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/api$ $scheme://$http_host/{{ .SandboxName }}/api/ permanent;
      rewrite ^/{{ .SandboxName }}/alt/api$ $scheme://$http_host/{{ .SandboxName }}/alt/api/ permanent;
      rewrite ^/{{ .SandboxName }}/api(/|$)(.*)$ /api/$2 break;
      rewrite ^/{{ .SandboxName }}/alt/api(/|$)(.*)$ /alt/api/$2 break;
      rewrite ^/{{ .SandboxName }}/sandbox-ctrl(/|$)(.*)$ /sandbox-ctrl/$2 break;
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-sandbox-ctrl&sbox={{ .SandboxName }}
    {{- end }}
  labels: {}
  tls:

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s

user:
  swagger:
    enabled: {{ .UserSwagger }}
codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-sandbox-ctrl"

meepOrigin: core
