# Default values for meep-platform-ctrl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-platform-ctrl

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  altPort: 8080
  dependency: kube-dns

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-platform-ctrl
  tag: latest
  pullPolicy: Always
  env:
    MEEP_MAX_SESSIONS: "10"
    MEEP_OAUTH_REDIRECT_URI: "https://<my-platform-fqdn>/platform-ctrl/v1/authorize"
  envSecret:
    MEEP_SESSION_KEY:
      name: meep-session
      key: encryption-key
    MEEP_OAUTH_GITHUB_CLIENT_ID:
      name: github-secret
      key: client-id
    MEEP_OAUTH_GITHUB_SECRET:
      name: github-secret
      key: secret
    MEEP_OAUTH_GITLAB_CLIENT_ID:
      name: gitlab-secret
      key: client-id
    MEEP_OAUTH_GITLAB_SECRET:
      name: gitlab-secret
      key: secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: ''
      paths:
        - /
        - /platform-ctrl
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/api$ $scheme://$http_host/api/ permanent;
      rewrite ^/alt$ $scheme://$http_host/alt/ permanent;
      rewrite ^/alt/api$ $scheme://$http_host/alt/api/ permanent;
  labels: {}
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-platform-ctrl"

user:
  frontend:
    enabled: false
    location: "<WORKDIR>/user/frontend"
    mountpath: "/user-frontend"

  swagger:
    enabled: false
    location: "<WORKDIR>/user/swagger"
    mountpath: "/user-swagger"

meepOrigin: core
