# Default values for meep-platform-ctrl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-platform-ctrl

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  altPort: 8080
  dependency: kube-dns

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-platform-ctrl
  tag: latest
  pullPolicy: Always
  env:
  envSecret:
    MEEP_SESSION_KEY:
      name: meep-session
      key: encryption-key

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /
        - /platform-ctrl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-platform-ctrl
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/api$ $scheme://$http_host/api/ permanent;
      rewrite ^/alt$ $scheme://$http_host/alt/ permanent;
      rewrite ^/alt/api$ $scheme://$http_host/alt/api/ permanent;
  labels: {}
  tls:

codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-platform-ctrl"

user:
  frontend:
    enabled: false
    location: "<WORKDIR>/user/frontend"
    mountpath: "/user-frontend"

  swagger:
    enabled: false
    location: "<WORKDIR>/user/swagger"
    mountpath: "/user-swagger"

meepOrigin: core
