# Default values for meep-mon-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-mon-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependencies:
    system:
      - kube-dns
    namespace:

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-mon-engine
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SVC_PATH: /mon-engine/v1
    # Provide comma-separated list of expected pods to be monitored
    MEEP_DEPENDENCY_PODS: ""
    MEEP_CORE_PODS: ""
    MEEP_SANDBOX_PODS: ""
  envSecret:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /mon-engine
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/auth-url: <-- set by 'meepctl deploy' when auth enabled

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s
    
codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-mon-engine"

meepOrigin: core
