# Default values for meep-mon-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-mon-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependency: kube-dns

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-mon-engine
  tag: latest
  pullPolicy: Always
  env:
    # Provide comma-separated list of expected pods to be monitored
    MEEP_DEPENDENCY_PODS: ""
    MEEP_CORE_PODS: ""
    MEEP_SANDBOX_PODS: ""
  envSecret:
    MEEP_SESSION_KEY:
      name: meep-session
      key: encryption-key
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /mon-engine
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-mon-engine

codecov:
  enabled: false

meepOrigin: core
