# Default values for meep-mg-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-mg-manager

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependency: kube-dns

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists

image:
  repository: meep-docker-registry:30001/meep-mg-manager
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}

service:
  name: meep-mg-manager
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/mgm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/mgm(/|$)(.*)$ /mgm/$2 break;
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-mg-manager&sbox={{ .SandboxName }}
    {{- end }}
  labels: {}
  tls:

codecov:
  enabled: false

meepOrigin: core
