type: s3
config:
  bucket: thanos-archive
  endpoint: advantedge.testfqdn.dev
  access_key: admin
  secret_key: password
  insecure: false
  signature_version2: false
  http_config:
    idle_conn_timeout: 1m30s
    response_header_timeout: 2m
    insecure_skip_verify: false
