apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "meep-webhook.fullname" . }}
  labels:
    app: {{ template "meep-webhook.name" . }}
    chart: {{ template "meep-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    meepOrigin: {{ .Values.meepOrigin }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "meep-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "meep-webhook.name" . }}
        release: {{ .Release.Name }}
        meepOrigin: {{ .Values.meepOrigin }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
              protocol: {{ .Values.deployment.protocol }}
          args:
            - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      terminationGracePeriodSeconds: 5
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ template "meep-webhook.fullname" . }}
        - name: webhook-config
          configMap:
            name: {{ .Values.configMap }}
      initContainers:
        - name: init-{{ .Values.deployment.dependency.redis }}
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nslookup {{ .Values.deployment.dependency.redis }} ; do echo waiting for {{ .Values.deployment.dependency.redis }}; sleep 0.25; done;']
        - name: init-{{ .Values.deployment.dependency.coredns }}
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nslookup {{ .Values.deployment.dependency.coredns }}.kube-system ; do echo waiting for {{ .Values.deployment.dependency.coredns }}; sleep 0.25; done;']
