{{- if .Values.letsEncrypt.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "meep-ingress-certs.fullname" . }}
  labels:
    app: {{ template "meep-ingress-certs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if .Values.letsEncrypt.acme.prod }}
    cert-manager.io/cluster-issuer: {{ .Values.letsEncrypt.issuer }}-prod
    {{- else }}
    cert-manager.io/cluster-issuer: {{ .Values.letsEncrypt.issuer }}-staging
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: "/letsencrypt/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.letsEncrypt.defaultBackend.service.name }}
                port:
                  number: {{ .Values.letsEncrypt.defaultBackend.service.port }}
  tls:
    - secretName: {{ .Values.letsEncrypt.tls.secret }}
      hosts:
      - {{ .Values.letsEncrypt.tls.host }}
{{- end }}
