openapi: 3.0.2
info:
  title: MEC Demo 3 API
  description: This section describes how to use AdvantEdge mec services with a scenario
    demonstrating use-case 1 - 3
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 0.0.1
servers:
- url: http://10.190.115.162:8093
paths:
  /register/app:
    post:
      tags:
      - frontend
      summary: Register with MEC Platform and create necessary resources
      description: Register with MEC Platform and create necessary resources
      operationId: Register
      responses:
        "200":
          description: Uppon success, a response body containing the app instance
            info is returned
          content: {}
        "400":
          description: Bad request. It is used to indicate that incorrect parameters
            were passed to the request.
          content: {}
        "404":
          description: Not found
          content: {}
  /info/application:
    get:
      tags:
      - frontend
      summary: Returns the application dynamic information
      description: Returns the application dynamic information
      operationId: GetPlatformInfo
      responses:
        "200":
          description: Upon success, a response body containing the app instance info
            is returned
          content: {}
        "400":
          description: Bad request. It is used to indicate that incorrect parameters
            were passed to the request.
          content: {}
        "404":
          description: Not found
          content: {}
  /info/logs:
    get:
      tags:
      - frontend
      summary: Returns activity logs
      description: Returns activity logs
      operationId: GetActivityLogs
      responses:
        "200":
          description: Uppon success, a response body containing logs of demo activities
            stored as strings will be returned
          content: {}
        "400":
          description: Bad request. It is used to indicate that incorrect parameters
            were passed to the request.
          content: {}
        "404":
          description: Not found
          content: {}
  /info/ams:
    get:
      tags:
      - frontend
      summary: Returns the list of AMS Devices
      description: Returns the list of AMS Devices
      operationId: GetAmsDevices
      responses:
        "200":
          description: Uppon success, a response body containing the list of ams log
            and context state stored as strings is returned
          content: {}
        "400":
          description: Bad request. It is used to indicate that incorrect parameters
            were passed to the request.
          content: {}
        "404":
          description: Not found
          content: {}
  /service/ams/update/{device}:
    put:
      tags:
      - frontend
      summary: Updates the list of AMS devices
      description: Updates the list of AMS devices
      operationId: UpdateAmsDevices
      parameters:
      - name: device
        in: path
        description: Start AMS service resource to track device name
        required: true
        style: simple
        explode: false
        schema: {}
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
  /service/ams/delete/{device}:
    delete:
      tags:
      - frontend
      summary: Delete an AMS device
      description: Delete an AMS device
      operationId: DeleteAmsDevice
      parameters:
      - name: device
        in: path
        description: Delete device from AMS service resource
        required: true
        style: simple
        explode: false
        schema: {}
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
  /info/application/delete:
    delete:
      tags:
      - frontend
      summary: Deregister with MEC Platform and delete associated resources
      description: Deregister with MEC Platform and delete associated resources
      operationId: Deregister
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request. It is used to indicate that incorrect parameters
            were passed to the request.
          content: {}
        "404":
          description: Not found
          content: {}
  /services/callback/amsevent:
    post:
      tags:
      - notification
      summary: Callback endpoint for AMS Notifications
      description: Callback endpoint for AMS Notifications
      operationId: AmsNotificationCallback
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
  /services/callback/service-availability:
    post:
      tags:
      - notification
      summary: Callback endpoint for MEC011 Notifications
      description: Callback endpoint for MEC011 Notifications
      operationId: ServiceAvailNotificationCallback
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
  /application/termination:
    post:
      tags:
      - notification
      summary: Callback endpoint for MEC011 app-termination notifications
      description: Callback endpoint for MEC011 app-termination notifications
      operationId: AppTerminationNotificationCallback
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
  /application/transfer:
    post:
      tags:
      - notification
      summary: Callback endpoint for MEC021 context-state transfer notification
      description: Callback endpoint for MEC021 context-state transfer notification
      operationId: ContextTransferNotificationCallback
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Not found
          content: {}
components:
  schemas: {}
x-original-swagger-version: "2.0"
