# Default values for meep-edge-platform-app-enablement.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount: meep-edge-platform-app-enablement

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependency: kube-dns

image:
  repository: meep-docker-registry:30001/meep-edge-platform-app-enablement
  tag: latest
  pullPolicy: Always
  env:
    MEEP_SANDBOX_NAME: {{ .SandboxName }}
    MEEP_HOST_URL: {{ .HostUrl }}

service:
  name: meep-edge-platform-app-enablement
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        - /{{ .SandboxName }}/edge-platform-app-enablement
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{ .SandboxName }}/rni(/|$)(.*)$ /rni/$2 break;
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-edge-platform-app-enablement&sbox={{ .SandboxName }}
    {{- end }}
  labels: {}
  tls:

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s
    
codecov:
  enabled: false

meepOrigin: core
