
---
- name: "Install helm with option --classic"
  snap:
    name: helm
    classic: yes
    channel: "{{ helm_version }}"
    state: present

- name: "Enable incubator charts"
  shell: "helm repo add incubator https://charts.helm.sh/incubator --kubeconfig .kube/config"
  tags: helm

- name: "Repo Update"
  shell: "helm repo update --kubeconfig .kube/config"
  tags: helm
